"""Update task and task_occurrence model

Revision ID: b974b414c864
Revises: ea8856d775cd
Create Date: 2024-08-24 20:18:31.066185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b974b414c864'
down_revision = 'ea8856d775cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_occurrences', schema=None) as batch_op:
        batch_op.alter_column('occurrence_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('task_occurrences', schema=None) as batch_op:
        batch_op.alter_column('occurrence_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
